// Ordered source graph for the legacy global-script application. Keep order stable:
// many files still communicate through globals while migration to ES modules proceeds.
export const buildGraph = {
  "css/style.css": {
    kind: "stylesheet",
    inputs: [
      "lib/codemirror/codemirror.css",
      "lib/codemirror/addon/dialog/dialog.css",
      "lib/codemirror/addon/scroll/simplescrollbars.css",
      "css/ui.css",
      "css/main.css",
      "css/glyphicons.css",
      "css/icons-halflings.css",
      "lib/perfect-scrollbar/perfect-scrollbar.css",
      "css/ripplejs.css",
    ],
  },
  "js/libs.js": {
    kind: "javascript",
    sourceMap: true,
    inputs: [
      "lib/jquery/jquery.min.js",
      "lib/jquery/jquery.mousewheel.min.13.js",
      "lib/perfect-scrollbar/perfect-scrollbar.min.js",
      "lib/ripplejs/ripplejs.js",
      "lib/threejs/three.min.js",
      "lib/threejs/stats.min.js",
      "lib/threejs/exporters/OBJExporter.js",
      "lib/threejs/exporters/GLTFExporter.js",
      "lib/threejs/controls/OrbitControls.js",
      "lib/threejs/utils/BufferGeometryUtils.js",
      "lib/tween/tween.min.js",
      "lib/colour/colour.js",
      "lib/chroma/chroma.min.js",
      "lib/rgbQuant/rgbQuant.js",
      "lib/jsmanipulate/jsmanipulate.min.js",
      "lib/download/download.js",
      "lib/gif/gif.js",
      "lib/jsfeat/jsfeat-min.js",
      "lib/jshint/jshint.js",
      "lib/jszip/jszip.min.js",
      "lib/jszip/jszip-utils.js",
      "lib/hammer/hammer.min.js",
      "lib/tuna/tuna.js",
      "lib/localForage/localforage.nopromises.min.js",
      "lib/jsinterpreter/acorn_interpreter.js",
      "lib/babel/babel.min.js",
      "lib/threejs/shaders/BleachBypassShader.js",
      "lib/threejs/shaders/ColorifyShader.js",
      "lib/threejs/shaders/ConvolutionShader.js",
      "lib/threejs/shaders/CopyShader.js",
      "lib/threejs/shaders/DotScreenShader.js",
      "lib/threejs/shaders/FilmShader.js",
      "lib/threejs/shaders/DigitalGlitch.js",
      "lib/threejs/shaders/HorizontalBlurShader.js",
      "lib/threejs/shaders/SepiaShader.js",
      "lib/threejs/shaders/VerticalBlurShader.js",
      "lib/threejs/shaders/VignetteShader.js",
      "lib/threejs/shaders/RGBShiftShader.js",
      "lib/threejs/shaders/TechnicolorShader.js",
      "lib/threejs/shaders/LuminosityHighPassShader.js",
      "lib/threejs/shaders/FocusShader.js",
      "lib/threejs/shaders/BrightnessContrastShader.js",
      "lib/threejs/shaders/HueSaturationShader.js",
      "lib/threejs/shaders/KaleidoShader.js",
      "lib/threejs/postprocessing/EffectComposer.js",
      "lib/threejs/postprocessing/RenderPass.js",
      "lib/threejs/postprocessing/BloomPass.js",
      "lib/threejs/postprocessing/FilmPass.js",
      "lib/threejs/postprocessing/GlitchPass.js",
      "lib/threejs/postprocessing/DotScreenPass.js",
      "lib/threejs/postprocessing/TexturePass.js",
      "lib/threejs/postprocessing/ShaderPass.js",
      "lib/threejs/postprocessing/MaskPass.js",
      "lib/threejs/postprocessing/UnrealBloomPass.js",
      "lib/ace/src/ace.js",
      "lib/ace/src/ext-language_tools.js",
      "lib/ace/src/mode-text.js",
      "lib/ace/src/mode-javascript_custom.js",
      "lib/ace/src/mode-assembly_6502.js",
      "lib/ace/src/mode-json.js",
      "lib/ace/src/mode-c64basic.js",
      "lib/typr/src/Typr.js",
      "lib/typr/src/Typr.U.js",
    ],
  },
  "js/main.js": {
    kind: "javascript",
    minify: true,
    sourceMap: true,
    inputs: [
      "js/security/jqueryHtmlPolicy.js",
      "js/utils/cssScrollbarSupport.js",
      "js/ui/ui.js",
      "js/ui/number.js",
      "js/ui/slider.js",
      "js/ui/menuBar.js",
      "js/ui/panel.js",
      "js/ui/popup.js",
      "js/ui/splitpanel.js",
      "js/ui/tabPanel.js",
      "js/ui/htmlPanel.js",
      "js/ui/webGLPanel.js",
      "js/ui/canvasPanel.js",
      "js/ui/canvasScrollPanel.js",
      "js/ui/dialog.js",
      "js/ui/mobilePanel.js",
      "js/ui/button.js",
      "js/ui/tree.js",
      "js/ui/progressBar.js",
      "js/utils/imageUtils.js",
      "js/utils/checkerboardPattern.js",
      "js/utils/imageLib.js",
      "js/utils/colorUtils.js",
      "js/utils/conversions.js",
      "js/utils/normalizeWheel.js",
      "js/utils/ase.js",
      "js/utils/aco.js",
      "js/utils/paramGraph.js",
      "js/utils/c64MulticolorTypeControl.js",
      "js/utils/textDialog.js",
      "js/utils/mobileDownload.js",
      "js/utils/textStore.js",
      "js/utils/touchVelocity.js",
      "js/utils/camera3dControls.js",
      "js/editor.js",
      "js/file/newProjectDialog.js",
      "js/file/projectNavigator.js",
      "js/file/projectShare.js",
      "js/file/projectNavigatorMobile.js",
      "js/file/startPage.js",
      "js/file/github.js",
      "js/file/gist.js",
      "js/file/createTemplateLink.js",
      "js/file/dropImage.js",
      "js/scripting/scripting.js",
      "js/scripting/scriptEditor.js",
      "js/shaderEffects/shaderEffects.js",
      "js/shaderEffects/shaderEffectControls.js",
      "js/shaderEffects/lotteCRTEffect.js",
      "js/shaderEffects/mattiasCRTEffect.js",
      "js/shaderEffects/noisyGlowEffect.js",
      "js/shaderEffects/shaders/blurShader.js",
      "js/shaderEffects/shaders/lotteCRTShader.js",
      "js/shaderEffects/shaders/mattiasCRTShader.js",
      "js/shaderEffects/shaders/noiseShader.js",
      "js/shaderEffects/shaders/vignetteShader.js",
      "js/config/config.js",
      "js/config/jsonEditor.js",
      "js/styles.js",
      "js/file/fileManager.js",
      "js/file/desktopFileManager.js",
      "js/file/document.js",
      "js/file/gdrive.js",
      "js/sprite/spriteEditor.js",
      "js/textMode/textModeEditor.js",
      "js/textMode/textModeEditorLayout.js",
      "js/textMode/textModeFile.js",
      "js/textMode/history.js",
      "js/textMode/info.js",
      "js/textMode/gridInfo.js",
      "js/textMode/mobileMenu.js",
      "js/textMode/graphic.js",
      "js/textMode/gridView3d.js",
      "js/textMode/gridView2d.js",
      "js/textMode/layers/layers.js",
      "js/textMode/layers/layerPropertiesDialog.js",
      "js/textMode/layers/layerGrid.js",
      "js/textMode/layers/layerBackground.js",
      "js/textMode/layers/layerRefImage.js",
      "js/textMode/layers/referenceImageDialog.js",
      "js/textMode/layers/layersMerge.js",
      "js/textMode/layers/layersFrames.js",
      "js/textMode/backgroundImage.js",
      "js/textMode/currentTile.js",
      "js/textMode/animationPreview.js",
      "js/textMode/tileSet/tileEditor.js",
      "js/textMode/tileSet/tileEditorMobile.js",
      "js/textMode/tileSet/tileEditorGrid.js",
      "js/textMode/tileSet/glyphEditor.js",
      "js/textMode/tileSet/glyphEditorCanvas.js",
      "js/textMode/tools.js",
      "js/textMode/tools/drawTools.js",
      "js/textMode/tools/pixelDrawTools.js",
      "js/textMode/tools/tilePalette.js",
      "js/textMode/tileSet/tilePaletteEditor.js",
      "js/textMode/tools/tilePaletteMobile.js",
      "js/textMode/tools/tilePaletteChooserMobile.js",
      "js/textMode/tools/blockPalette.js",
      "js/textMode/tools/drawToolsPopup.js",
      "js/textMode/tools/shapes.js",
      "js/textMode/tools/shapes3d.js",
      "js/textMode/tools/typing.js",
      "js/textMode/tools/pixelCharacterDraw.js",
      "js/textMode/tools/lineSegmentDraw.js",
      "js/textMode/tools/invertTool.js",
      "js/textMode/tools/cornersTool.js",
      "js/textMode/tools/pixelDraw.js",
      "js/textMode/tools/fill.js",
      "js/textMode/tools/select.js",
      "js/textMode/tools/select3d.js",
      "js/textMode/tools/pixelSelect.js",
      "js/textMode/tools/replaceColor.js",
      "js/textMode/tools/replaceCharacter.js",
      "js/textMode/tools/clearHiddenTiles.js",
      "js/textMode/tools/gridDimensionsDialog.js",
      "js/textMode/grid.js",
      "js/textMode/grid2d.js",
      "js/textMode/grid3d.js",
      "js/textMode/grid3dLayer.js",
      "js/textMode/frames/frames.js",
      "js/textMode/frames/frameTimeline.js",
      "js/textMode/frames/spriteFrames.js",
      "js/textMode/tileSet/tilePaletteDisplay.js",
      "js/textMode/tileSet/characterSetPresets.js",
      "js/textMode/tileSet/vectorPresets.js",
      "js/textMode/tileSet/tileSetManager.js",
      "js/textMode/tileSet/tileSet.js",
      "js/textMode/tileSet/tile3d.js",
      "js/textMode/tileSet/tileSetEditor.js",
      "js/textMode/tileSet/tileSetChoosePreset.js",
      "js/textMode/tileSet/characterSetChoosePresetMobile.js",
      "js/textMode/tileSet/tileSetImport.js",
      "js/textMode/tileSet/tileSetSave.js",
      "js/textMode/tileSet/chooseCharactersDialog.js",
      "js/textMode/tileSet/tilePickerPopup.js",
      "js/textMode/tileSet/tileMaterials.js",
      "js/textMode/blockSet/blockSetManager.js",
      "js/textMode/blockSet/blockSet.js",
      "js/textMode/blockSet/blockEditor.js",
      "js/textMode/color/colorPalettePresets.js",
      "js/textMode/color/customColorPalettePresets.js",
      "js/textMode/color/colorPaletteManager.js",
      "js/textMode/color/colorPaletteChoosePreset.js",
      "js/textMode/color/colorPaletteChoosePresetMobile.js",
      "js/textMode/color/colorPalette.js",
      "js/textMode/color/colorPickerPopup.js",
      "js/textMode/color/colorPickerMobile.js",
      "js/textMode/color/chooseColorsDialog.js",
      "js/textMode/color/colorPalettePanel.js",
      "js/textMode/color/colorEditor.js",
      "js/textMode/color/colorPaletteEditor.js",
      "js/textMode/color/colorPaletteEdit.js",
      "js/textMode/color/editColorPalette.js",
      "js/textMode/color/colorSubPalettes.js",
      "js/textMode/color/colorSubPalettePickerMobile.js",
      "js/textMode/color/colorPaletteSave.js",
      "js/textMode/color/colorPaletteLoad.js",
      "js/textMode/color/colorPaletteLoadFromURL.js",
      "js/textMode/color/colorPaletteDisplay.js",
      "js/textMode/imageEffects/imageEffects.js",
      "js/textMode/imageEffects/imageEffectsControl.js",
      "js/textMode/imageEffects/mirrorEffect.js",
      "js/textMode/imageEffects/rotateZoomEffect.js",
      "js/textMode/imageEffects/slitscanEffect.js",
      "js/textMode/imageEffects/imageParametersEffect.js",
      "js/textMode/imageEffects/noiseEffect.js",
      "js/textMode/imageEffects/imageShaderEffects.js",
      "js/textMode/imageEffects/crt2Shader.js",
      "js/textMode/imageEffects/ghostShader.js",
      "js/textMode/imageEffects/colorHalftoneShader.js",
      "js/textMode/imageEffects/wobbleShader.js",
      "js/textMode/imageEffects/noiseShader.js",
      "js/textMode/imageEffects/edgeShader.js",
      "js/textMode/imageEffects/bumpShader.js",
      "js/textMode/imageEffects/embossShader.js",
      "js/textMode/imageEffects/rainbowShader.js",
      "js/textMode/imageEffects/scanlinesShader.js",
      "js/textMode/imageEffects/plasmaShader.js",
      "js/textMode/imageEffects/badTVShader.js",
      "js/textMode/imageEffects/pixelateShader.js",
      "js/textMode/imageEffects/hexagonalPixelateShader.js",
      "js/textMode/imageEffects/diffusionShader.js",
      "js/textMode/imageEffects/TriangleBlurShader.js",
      "js/textMode/imageEffects/denoiseShader.js",
      "js/textMode/imageEffects/chromaKeyShader.js",
      "js/hexEditor/hexEditor.js",
      "js/textMode/import/importAssembly.js",
      "js/textMode/import/importC64Formats.js",
      "js/textMode/import/importC64SpriteFormats.js",
      "js/textMode/import/importSpriteImage.js",
      "js/textMode/import/viceSnapshotReader.js",
      "js/textMode/import/importC.js",
      "js/textMode/import/importSeq.js",
      "js/textMode/import/importCharPad.js",
      "js/textMode/import/importSpritePad.js",
      "js/textMode/import/importSpr.js",
      "js/textMode/export/exportFrameImage.js",
      "js/textMode/export/exportImage.js",
      "js/textMode/export/exportGif.js",
      "js/textMode/export/exportSvg.js",
      "js/textMode/export/exportPng.js",
      "js/textMode/export/exportPngMobile.js",
      "js/textMode/export/exportSpritePng.js",
      "js/textMode/export/exportGifMobile.js",
      "js/textMode/export/exportJson.js",
      "js/textMode/export/exportTxt.js",
      "js/textMode/export/exportPetsciiC.js",
      "js/textMode/export/exportPet.js",
      "js/textMode/export/exportBinaryData.js",
      "js/textMode/export/exportSpriteBinaryData.js",
      "js/textMode/export/exportC64Assembly.js",
      "js/textMode/export/exportMega65Assembly.js",
      "js/textMode/export/exportX16Assembly.js",
      "js/textMode/export/exportC64SpriteAssembly.js",
      "js/textMode/export/exportCharPad.js",
      "js/textMode/export/exportSpritePad.js",
      "js/textMode/export/exportSeq.js",
      "js/textMode/export/exportX16Basic.js",
      "js/textMode/c64export/c64Asm.js",
      "js/textMode/c64export/toPrg.js",
      "js/textMode/c64export/toPrgAdvanced.js",
      "js/textMode/c64export/exportC64Dialog.js",
      "js/textMode/c64export/exportC64.js",
      "js/textMode/c64export/exportC64ASM.js",
      "js/textMode/c64export/d64.js",
      "js/textMode/export3d/export3dGif.js",
      "js/textMode/export3d/exportVox.js",
      "js/textMode/export3d/exportObj.js",
      "js/textMode/api/textMode.js",
      "js/textMode/api/screenApi.js",
      "js/textMode/api/graphicApi.js",
      "js/textMode/api/colorPalette.js",
      "js/music/music.js",
      "js/music/musicHistory.js",
      "js/music/playbackControls.js",
      "js/music/musicEditTools.js",
      "js/music/musicScripting.js",
      "js/music/pattern.js",
      "js/music/patternView.js",
      "js/music/patternViewPopup.js",
      "js/music/track.js",
      "js/music/trackView.js",
      "js/music/keyboardCanvas.js",
      "js/music/channelInfo.js",
      "js/music/pitchDetect.js",
      "js/music/notes.js",
      "js/music/drummer.js",
      "js/music/bassist.js",
      "js/music/oscilloscope.js",
      "js/music/historyGraph.js",
      "js/music/scales.js",
      "js/music/sid/jsSID.js",
      "js/music/sid/sidPlayer.js",
      "js/music/sid/jsSID2.js",
      "js/music/sid/sidPlayer2.js",
      "js/music/sid/sidPatternPlayer.js",
      "js/music/sid/sidEffectsChooser.js",
      "js/music/sid/instruments.js",
      "js/music/sid/editInstrument.js",
      "js/music/sid/filters.js",
      "js/music/sid/editFilter.js",
      "js/music/sid/sidPlayerData.js",
      "js/music/sid/songData.js",
      "js/music/sid/sidFile.js",
      "js/music/sid/export/exportGoatTracker.js",
      "js/music/sid/export/exportSid.js",
      "js/music/sid/export/exportPRG.js",
      "js/codeEditor/codeEditor.js",
      "js/codeEditor/textEditor.js",
      "js/assembler/assembler.js",
      "js/assembler/assemblerEditor.js",
      "js/assembler/buildControls.js",
      "js/assembler/assemblerOutput.js",
      "js/assembler/acmeParser.js",
      "js/assembler/assemblerFiles.js",
      "js/assembler/c64Asm.js",
      "js/assembler/assemblerPreprocessor.js",
      "js/assembler/asmParser.js",
      "js/assemblerUtils/calculator.js",
      "js/assemblerUtils/mos6502Opcodes.js",
      "js/assemblerUtils/c64MemoryMap.js",
      "js/debugger/dbgFont.js",
      "js/debugger/dbgDisassembly.js",
      "js/debugger/dbgBreakpoints.js",
      "js/debugger/dbgMemory.js",
      "js/debugger/dbgScripting.js",
      "js/debugger/dbgC64Basic.js",
      "js/debugger/basicTokeniser.js",
      "js/debugger/dbgC64Drive.js",
      "js/debugger/dbgRegisters.js",
      "js/debugger/dbgCharset.js",
      "js/debugger/dbgC64Bitmap.js",
      "js/debugger/dbgC64CharEditor.js",
      "js/debugger/dbgC64Colors.js",
      "js/debugger/dbgSID.js",
      "js/debugger/dbgSprites.js",
      "js/debugger/exportC64SpriteData.js",
      "js/debugger/dbgC64SpriteEditor.js",
      "js/debugger/mos6510Opcodes.js",
      "js/c64/c64Debugger.js",
      "js/c64/c64DebuggerExportHTML.js",
      "js/c64/c64GistShare.js",
      "js/c64/c64DebuggerCompact.js",
      "js/c64/c64Joystick.js",
      "js/c64/c64Scripting.js",
      "js/c64/c64Sound.js",
      "js/c64/c64Colors.js",
      "js/c64/c64d64.js",
      "js/c64/c64OnscreenJoystick.js",
      "js/c64/c64OnscreenKeyboard.js",
      "js/c64/roms/charROM.js",
    ],
  },
  "js/features/image-import.js": {
    kind: "javascript",
    minify: true,
    sourceMap: true,
    inputs: [
      "js/textMode/import2d/importColorUtils.js",
      "js/textMode/import2d/basicImport.js",
      "js/textMode/import2d/mobileImport.js",
      "js/textMode/import2d/shaderImport2.js",
      "js/textMode/import2d/importImage.js",
      "js/textMode/import2d/importImageMobile.js",
      "js/textMode/import2d/shaderImportEditor.js",
    ],
  },
};

// Native modules are discovered from these governed roots. The composition root
// is the only module allowed to touch browser globals; every other dependency is
// injected through a layer-specific public entry point.
export const moduleGraph = {
  entry: "js/bootstrap.mjs",
  sourceRoots: ["js/bootstrap.mjs", "js/modules"],
  globalAccess: ["js/bootstrap.mjs"],
  layers: [
    {
      name: "bootstrap",
      root: "js/bootstrap.mjs",
      mayImport: ["feature-adapter", "application", "infrastructure", "domain"],
    },
    {
      name: "feature-adapter",
      root: "js/modules/feature-adapters/",
      mayImport: ["application", "domain"],
    },
    {
      name: "application",
      root: "js/modules/application/",
      mayImport: ["application", "domain"],
    },
    {
      name: "infrastructure",
      root: "js/modules/infrastructure/",
      mayImport: ["infrastructure", "application", "domain"],
    },
    {
      name: "domain",
      root: "js/modules/domain/",
      mayImport: ["domain"],
    },
  ],
  publicEntries: [
    "js/modules/application/featureRegistry.mjs",
    "js/modules/feature-adapters/imageImportFeature.mjs",
    "js/modules/infrastructure/classicScriptLoader.mjs",
  ],
  cycleExceptions: [],
};

// New files may enter the ordered legacy application graph only through a
// temporary, reviewed exception. Keep this empty during normal module work.
// Exception values require { reason, expires: "YYYY-MM-DD" } and are verified
// against tests/fixtures/legacy-main-graph.json.
export const legacyGraphExceptions = {};

export const copiedScripts = {
  "js/htmlPolicy.js": "js/security/htmlPolicy.js",
  "js/startup.js": "js/startup.js",
  "js/storageManager.js": "js/utils/storageManager.js",
  "js/githubApi.js": "js/file/githubApi.js",
  "js/githubClient.js": "js/file/githubClient.js",
  "js/acmeAssembler.js": "js/assembler/acmeAssembler.js",
  "js/ca65Assembler.js": "js/assembler/ca65Assembler.js",
  "js/c64/c64.js": "js/c64/c64.js",
};
